server:
  port: 8081
spring:
  application:
    name: supplier

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_ADDRESS:http://localhost:8762/eureka}
message:
  hello: it's a supplier
